version: '3.1'

services:
  db:
    image: arm64v8/mysql:5.7 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: example

  app:
    image: nextcloud:apache  
    platform: linux/arm64  
    ports:
      - 8081:80 
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: example
      MYSQL_HOST: db
